### ISSUE TITLE
Vector graphics

### ISSUE THREAD

**Issue by n1kStas** [ManakhovN/FigmaToUnityImporter#14]
Please add the ability to import in SVG format. https://docs.unity3d.com/Packages/com.unity.vectorgraphics@2.0/manual/index.html

**Comment by ManakhovN** [comment]
> Please add the ability to import in SVG format. https://docs.unity3d.com/Packages/com.unity.vectorgraphics@2.0/manual/index.html

Added. Try it.

**Comment by barnabe-perspectives** [comment]
Hello @ManakhovN ,
The following error now appears since your last commit and i guess its related : 

`Library\PackageCache\com.manakhovn.figma_to_unity_importer@d4ecf1dfb5\Editor\ImageUtils.cs(5,13): error CS0234: The type or namespace name 'VectorGraphics' does not exist in the namespace 'Unity' (are you missing an assembly reference?)
`

**Comment by ManakhovN** [comment]
@barnabe-perspectives Oh, you are right. My bad. Pushed changes. Must be fixed now.
