### ISSUE TITLE
All downloaded sprites are broken

### ISSUE THREAD

**Issue by dmq-ar** [ManakhovN/FigmaToUnityImporter#15]
Hello! I'm getting a weird picture after nodes import and all sprites in Renders folder have size of 32 B.
Unity 2021.1.22

![image](https://user-images.githubusercontent.com/62610948/135218319-9ab976a1-33cf-4b25-a79e-37308a890971.png)

**Comment by ManakhovN** [comment]
@dmq-ar  Hello. I had this kind of behavior before and I think the problem may be In Figma API. Sometimes it doesn't give proper images. Try to get a new authorization token and wait for a little, that's the only advice I can give. This bug is not stably reproducible so it is hard to track what is wrong there. Let's keep this issue open, maybe I will check it again later.

**Comment by dmq-ar** [comment]
> @dmq-ar Hello. I had this kind of behavior before and I think the problem may be In Figma API. Sometimes it doesn't give proper images. Try to get a new authorization token and wait for a little, that's the only advice I can give. This bug is not stably reproducible so it is hard to track what is wrong there. Let's keep this issue open, maybe I will check it again later.

Thank you for the answer! I've tried Unity 2020.3.18 and it worked. I thought it's a Unity version issue, but now I see it became fixed because of my re-autharization.
