### ISSUE TITLE
Import broken

### ISSUE THREAD

**Issue by bakwc** [ManakhovN/FigmaToUnityImporter#23]
On a real project - result is completely broken, don't worth it.
Left - original, right - result

https://drive.google.com/file/d/1OFjRP_Kuf5KTQkWjx5qHoSAZAFCHLyPJ/view?usp=sharing

**Comment by ManakhovN** [comment]
@bakwc Hello. Obviously, not all features are supported yet and some of them are impossible to realize in unity. For example, blurred background on bottom tabs on your picture is hard to quickly implement without losing any performance. Probably I need to write about all the limitations and supported features. But it would be nice If you share a Figma project with your layout so I could fix some of the problems.

**Comment by bakwc** [comment]
Sure. Give me your e-mail and I will give you access.

**Comment by ManakhovN** [comment]
@bakwc My e-mail is nadirmanakhov@gmail.com
1. Ok I will check where I did a mistake in applying the UI masks. 
2. Possibly the problem is in Layer type. It supports only the "normal" one.
3. Fonts. It is a tricky one. I can't download it through the Figma API. And a lot of fonts are licensed, so I am not sure that I can just download them from somewhere. Also, TMP asset needs to be generated for certain font and with proper glyphs. So just read the instruction.
4. You can set render mode for the root object, so it will take an image of the whole diamond, not its parts.

Yes, I can commercialize it. But taking money from people will force me to support this tool 24/7. So I don't like this idea.
As an open-source project, it gives the opportunity to contribute or make other tools based on it. But still, not so many people contributed here. Unfortunately, it is hard to find enough time to polish this project.

**Comment by bakwc** [comment]
You can take fonts from google-fonts, they even have some sort-of api, https://developers.google.com/fonts/docs/css2
This is the recommended way to extract figma fonts even manually.
